# 하이퍼파라미터 탐색 -> grid search
method: 'grid'

metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42

    model: 
      value: 'autoencoder'
    task:
      value: 'gaze'
    segment:
      value: 12

    # 3초x30fps = 90 프레임
    segment_length:
      value: 90

    # 은닉 레이어 1개, 차원 128
    hidden_sizes: 
      #value: [512]
      value: [128]
    
    alpha:
      value: 0
    lr: 
      value: 1e-3
    weight_decay: 
      value: 1e-5
    batch_size:
      value: 16

    # 분산학습 방식: distributed data parallel
    strategy:
      value: 'ddp'
    
    epoch:
      value: 1

    ckpt:
      value: 'checkpoints/test'