method: 'grid'
name: 'multi'
metric: 
    name: 'val_f1'
    goal: 'maximize'   

parameters: 
    seed:
      value: 42

    model:
      value: 'masktransformer'

    hidden_size: 
      value: 1024
    segment:
      value: 12  # 6 * 180 / 4 * 270 / 2 * 540
    segment_length:
      value: 90
    frozen:
      value: True
    
    pretrained:
      value: 'pretrained'

    # 누락된 피처를 어떻게 채울지. -> 이 경우 이전 값 복사
    feature_filling:
      value: 'repeat'

    lr: 
      value: 3e-5
    weight_decay: 
      value: 1e-6
    batch_size:
      value: 32
    strategy:
      value: 'ddp_find_unused_parameters_true'

    test_idx:
      values: [30]

    # transformer 블록의 층 개수 (디코더 12 layers)
    n_layer:
      value: 12 # 12

    # multihead attention head 개수
    n_head:
      value: 16 # 16

    activation_function: 
      value: 'gelu'
    n_ctx:
      value: 216

    # Residual Dropout
    resid_pdrop:
      value: 0.1
    
    # Attention Dropout
    attn_pdrop:
      value: 0.1
    n_bundle:
      value: 18

    epoch:
      value: 50

    ckpt:
      value: 'checkpoints/ablation/continuous'

    comment:
      value: 'multi with continuous featurization'

    