method: 'grid'
name: 'vqvae'
metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42
    model:
      value: 'vqvae'

    task:
      values: ['gaze', 'headpose', 'pose']
    segment:
      value: 12 # 6 * 180 / 4 * 270 / 2 * 540
    segment_length:
      value: 90

    test_idx:
      values: [30]

    hidden_sizes: 
      value: [1024]

    # CNN latent featur map 개수 -> 나중에 이 128개가 codebook 임베딩으로 매핑
    h_dim:
      value: 128
    
    # CNN kernel 크기
    kernel:
      value: 3

    stride:
      value: 1
    
    # VQ-VAE 내부 Residual block 설정
    res_h_dim:
      value: 32
    n_res_layers:
      value: 2
    
    # codebook 벡터 개수
    n_embeddings:
      value: 512

    # codebook 벡터 차원
    embedding_dim:
      value: 32
    beta:
      value: 0.25

    lr: 
      value: 5e-4
    weight_decay: 
      value: 1e-6
    batch_size:
      value: 32
    strategy:
      value: 'ddp_find_unused_parameters_true'
    

    epoch:
      value: 1

    ckpt:
      value: 'checkpoints/vqvae/test'

    